### ISSUE TITLE
System Info has no Info

### ISSUE THREAD

**Issue by enzanki-ars** [JimmyAppelt/Snaz#77] opened 2016-06-08 23:11 UTC
As shown below, when I open the system info tab, no info is displayed and the following errors appear. 
![snaz-error1](https://cloud.githubusercontent.com/assets/8580211/15914182/bdf29e3a-2dac-11e6-8d62-0090a7a41b65.png)
![snaz-error2](https://cloud.githubusercontent.com/assets/8580211/15914183/bdf30f78-2dac-11e6-863f-87f5b005b968.png)
![snaz-error3](https://cloud.githubusercontent.com/assets/8580211/15914181/bdf14e54-2dac-11e6-8f1e-abd714ceed4d.png)

**Comment by JimmyAppelt** [comment] 2016-06-09 09:47
Hi @enzanki-ars,

This is a duplicate of issue #71 
Check the issue out and reinitialize you're windows performance counters.

**Comment by enzanki-ars** [comment] 2016-06-09 13:00
Wow. I completely missed that issue. Thank you. Might it be possible to add a link to the wiki entry when that error occurs?

**Comment by JimmyAppelt** [comment] 2016-06-09 13:46
Yes sir, that would be possible ... 9/10 it would be that issue ... but there could other reasons to of coarse.

**Comment by enzanki-ars** [comment] 2016-06-09 20:35
It still might be a good idea to catch the error an show a link to the solution. I do not see any other issues with this error, and I doubt that there will be a different underling issue there.

**Comment by JimmyAppelt** [comment] 2016-06-27 21:50
If the error appears, users will be prompted with the wiki link to the solution. *(from 1.12.3.0)*

**Closed by JimmyAppelt** 2016-06-27 21:50 UTC
Labels: duplicate, enhancement
