### ISSUE TITLE
Expand use of variables to different components

### ISSUE THREAD

**Issue by paulheu** [JimmyAppelt/Snaz#41] opened 2016-01-02 09:37 UTC
Would be cool is variables would be usable in different parts of Snaz. For instance have $viewers be available in the text line changer so I can rotate a line showing viewers there..

Also agree it would be useful if the Twitch tab would grab general numbers such as followers and subs (total/today) and not just viewers ..

**Comment by JimmyAppelt** [comment] 2016-01-02 12:59
Hey @paulheu,

> Would be cool is variables would be usable in different parts of Snaz. For instance have $viewers be available in the text line changer so I can rotate a line showing viewers there..

This is actually a duplicate of #21 :smile: 

> Also agree it would be useful if the Twitch tab would grab general numbers such as followers and subs (total/today) and not just viewers ..

Actually also a duplicate of #22, except for the followers of today ... You can parse all this kind information with dynamic files already "today". (You can get a dynamic files pack in discord chat).

For followers per session it's a bit different ... i would need to implement a follower/subscriber notification or some sore ... to count them. This will involve the writing of a new feature, for that i have to consider if its worth it or not ... as there are lots of software's already that focus themselves on notifications from followers and subs already.

**Comment by paulheu** [comment] 2016-01-02 13:28
While there's quite a few tools for that, there is nothing like the textline changer in Snaz and it's the perfect place to cycle through these statistics while not using that much space on the overlay.. If it would be possible to add the content of another textfile to the cycle that would obviously work with dynamic files then, yes.

**Closed** 2017-09-30 01:26 UTC
Labels: Duplicate, Type: Request
