### ISSUE TITLE
iTunes doesn't work with it.

### ISSUE THREAD

**Issue by SpillProff** [JimmyAppelt/Snaz#191] opened 2017-09-22 05:42 UTC
I wanted to use Spotify but my mp3's wouldn't work so I tried to use iTunes but then it thinks iTunes isn't open or it doesn't know iTunes is playing. About to stream later.

**Comment by rob2ee** [comment] 2017-09-23 17:45
I opened a ticket for this 7 days ago.  No answer?

**Comment by JimmyAppelt** [comment] 2017-09-23 17:52
@rob2ee  I know 

Patience dear .. I still did not found the time to look at it.

This issue is also a duplicate of #190

**Closed by JimmyAppelt** 2017-09-23 17:52 UTC

**Comment by rob2ee** [comment] 2017-10-02 22:51
This is REALLY frustrating for me.  I really love SNAZ.  Is there an alternative app that works with iTunes that I can use until this is fixed?

**Comment by JimmyAppelt** [comment] 2017-10-03 07:47
All programs using the same com component, which communicates with iTunes have the same error. So It's highly likely the new iTunes itself that invokes it.

**Comment by rob2ee** [comment] 2017-10-11 22:55
Crap, is there a way to get iTunes to fix that?
