### ISSUE TITLE
Add Now Playing Support for Google Play Music Desktop Player

### ISSUE THREAD

**Issue by churchymayer** [JimmyAppelt/Snaz#185] opened 2017-08-29 19:20 UTC
I personally use Google Play Music for streaming music. On Desktop there is a fan made app for it, that adds some nice features , including a JSON file outputting all relevant data about the current song. 
![cuserschurchymayerappdataroaminggoogle_play__2017-08-29_21-16-39](https://user-images.githubusercontent.com/18197550/29839677-6443bffa-8cff-11e7-99c2-39ff72c8136f.png)
The file is located in %AppData%\Roaming\Google Play Music Desktop Player\json_store\playback.json
As this file is updated constantly i was hoping that it could be integrated into Snaz as OBS doesn't support JSON files to be displayed, at least i haven't found anything

**Comment by JimmyAppelt** [comment] 2017-08-29 19:23
Duplicate of #185 

(Request for Snaz are also currently closed)

Regards

**Closed by JimmyAppelt** 2017-08-29 19:23 UTC
Labels: Duplicate
